<?php
/**
 * CacheApi
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cloudinary\Cloudinary;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Cloudinary\ApiException;
use Cloudinary\Configuration;
use Cloudinary\HeaderSelector;
use Cloudinary\ObjectSerializer;

/**
 * CacheApi Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CacheApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation invalidate
     *
     * Invalidate the cache
     *
     * @param  string $authorization authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheInvalidateRequestPayload $cache_invalidate_request_payload Payload to invalidate the cache (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invalidate($authorization, $cloud_name, $cache_invalidate_request_payload)
    {
        $this->invalidateWithHttpInfo($authorization, $cloud_name, $cache_invalidate_request_payload);
    }

    /**
     * Operation invalidateWithHttpInfo
     *
     * Invalidate the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheInvalidateRequestPayload $cache_invalidate_request_payload Payload to invalidate the cache (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invalidateWithHttpInfo($authorization, $cloud_name, $cache_invalidate_request_payload)
    {
        $request = $this->invalidateRequest($authorization, $cloud_name, $cache_invalidate_request_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation invalidateAsync
     *
     * Invalidate the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheInvalidateRequestPayload $cache_invalidate_request_payload Payload to invalidate the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invalidateAsync($authorization, $cloud_name, $cache_invalidate_request_payload)
    {
        return $this->invalidateAsyncWithHttpInfo($authorization, $cloud_name, $cache_invalidate_request_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invalidateAsyncWithHttpInfo
     *
     * Invalidate the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheInvalidateRequestPayload $cache_invalidate_request_payload Payload to invalidate the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invalidateAsyncWithHttpInfo($authorization, $cloud_name, $cache_invalidate_request_payload)
    {
        $returnType = '';
        $request = $this->invalidateRequest($authorization, $cloud_name, $cache_invalidate_request_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invalidate'
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheInvalidateRequestPayload $cache_invalidate_request_payload Payload to invalidate the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invalidateRequest($authorization, $cloud_name, $cache_invalidate_request_payload)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling invalidate'
            );
        }
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling invalidate'
            );
        }
        // verify the required parameter 'cache_invalidate_request_payload' is set
        if ($cache_invalidate_request_payload === null || (is_array($cache_invalidate_request_payload) && count($cache_invalidate_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cache_invalidate_request_payload when calling invalidate'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/cache/invalidate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($cache_invalidate_request_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($cache_invalidate_request_payload));
            } else {
                $httpBody = $cache_invalidate_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation warmup
     *
     * Warm up the cache
     *
     * @param  string $authorization authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheWarmupRequestPayload $cache_warmup_request_payload Payload to warm up the cache (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Model\CacheWarmupSuccessResponse
     */
    public function warmup($authorization, $cloud_name, $cache_warmup_request_payload)
    {
        list($response) = $this->warmupWithHttpInfo($authorization, $cloud_name, $cache_warmup_request_payload);
        return $response;
    }

    /**
     * Operation warmupWithHttpInfo
     *
     * Warm up the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheWarmupRequestPayload $cache_warmup_request_payload Payload to warm up the cache (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Model\CacheWarmupSuccessResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function warmupWithHttpInfo($authorization, $cloud_name, $cache_warmup_request_payload)
    {
        $request = $this->warmupRequest($authorization, $cloud_name, $cache_warmup_request_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Model\CacheWarmupSuccessResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Model\CacheWarmupSuccessResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Model\CacheWarmupSuccessResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Model\CacheWarmupSuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation warmupAsync
     *
     * Warm up the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheWarmupRequestPayload $cache_warmup_request_payload Payload to warm up the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function warmupAsync($authorization, $cloud_name, $cache_warmup_request_payload)
    {
        return $this->warmupAsyncWithHttpInfo($authorization, $cloud_name, $cache_warmup_request_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation warmupAsyncWithHttpInfo
     *
     * Warm up the cache
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheWarmupRequestPayload $cache_warmup_request_payload Payload to warm up the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function warmupAsyncWithHttpInfo($authorization, $cloud_name, $cache_warmup_request_payload)
    {
        $returnType = '\Cloudinary\Model\CacheWarmupSuccessResponse';
        $request = $this->warmupRequest($authorization, $cloud_name, $cache_warmup_request_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'warmup'
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\CacheWarmupRequestPayload $cache_warmup_request_payload Payload to warm up the cache (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function warmupRequest($authorization, $cloud_name, $cache_warmup_request_payload)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling warmup'
            );
        }
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling warmup'
            );
        }
        // verify the required parameter 'cache_warmup_request_payload' is set
        if ($cache_warmup_request_payload === null || (is_array($cache_warmup_request_payload) && count($cache_warmup_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cache_warmup_request_payload when calling warmup'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/cache/warmup';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($cache_warmup_request_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($cache_warmup_request_payload));
            } else {
                $httpBody = $cache_warmup_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
