<?php
/**
 * MediaTargetApi
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cloudinary\Cloudinary;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Cloudinary\ApiException;
use Cloudinary\Configuration;
use Cloudinary\HeaderSelector;
use Cloudinary\ObjectSerializer;

/**
 * MediaTargetApi Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaTargetApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createMediaTarget
     *
     * Create a new Media Target
     *
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\MediaTargetCreatePayload $media_target_create_payload Payload to create Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Model\MediaTarget
     */
    public function createMediaTarget($cloud_name, $media_target_create_payload)
    {
        list($response) = $this->createMediaTargetWithHttpInfo($cloud_name, $media_target_create_payload);
        return $response;
    }

    /**
     * Operation createMediaTargetWithHttpInfo
     *
     * Create a new Media Target
     *
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\MediaTargetCreatePayload $media_target_create_payload Payload to create Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Model\MediaTarget, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMediaTargetWithHttpInfo($cloud_name, $media_target_create_payload)
    {
        $request = $this->createMediaTargetRequest($cloud_name, $media_target_create_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Cloudinary\Model\MediaTarget' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Model\MediaTarget', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Model\MediaTarget';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Model\MediaTarget',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMediaTargetAsync
     *
     * Create a new Media Target
     *
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\MediaTargetCreatePayload $media_target_create_payload Payload to create Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaTargetAsync($cloud_name, $media_target_create_payload)
    {
        return $this->createMediaTargetAsyncWithHttpInfo($cloud_name, $media_target_create_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMediaTargetAsyncWithHttpInfo
     *
     * Create a new Media Target
     *
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\MediaTargetCreatePayload $media_target_create_payload Payload to create Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaTargetAsyncWithHttpInfo($cloud_name, $media_target_create_payload)
    {
        $returnType = '\Cloudinary\Model\MediaTarget';
        $request = $this->createMediaTargetRequest($cloud_name, $media_target_create_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMediaTarget'
     *
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  \Cloudinary\Model\MediaTargetCreatePayload $media_target_create_payload Payload to create Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMediaTargetRequest($cloud_name, $media_target_create_payload)
    {
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling createMediaTarget'
            );
        }
        // verify the required parameter 'media_target_create_payload' is set
        if ($media_target_create_payload === null || (is_array($media_target_create_payload) && count($media_target_create_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $media_target_create_payload when calling createMediaTarget'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/media_targets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($media_target_create_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($media_target_create_payload));
            } else {
                $httpBody = $media_target_create_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteMediaTarget
     *
     * Delete the Media Target
     *
     * @param  string $authorization authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteMediaTarget($authorization, $cloud_name, $id)
    {
        $this->deleteMediaTargetWithHttpInfo($authorization, $cloud_name, $id);
    }

    /**
     * Operation deleteMediaTargetWithHttpInfo
     *
     * Delete the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteMediaTargetWithHttpInfo($authorization, $cloud_name, $id)
    {
        $request = $this->deleteMediaTargetRequest($authorization, $cloud_name, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteMediaTargetAsync
     *
     * Delete the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMediaTargetAsync($authorization, $cloud_name, $id)
    {
        return $this->deleteMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteMediaTargetAsyncWithHttpInfo
     *
     * Delete the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id)
    {
        $returnType = '';
        $request = $this->deleteMediaTargetRequest($authorization, $cloud_name, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMediaTarget'
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteMediaTargetRequest($authorization, $cloud_name, $id)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling deleteMediaTarget'
            );
        }
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling deleteMediaTarget'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteMediaTarget'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/media_targets/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMediaTarget
     *
     * Get the Media Target
     *
     * @param  string $authorization authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Model\MediaTarget
     */
    public function getMediaTarget($authorization, $cloud_name, $id)
    {
        list($response) = $this->getMediaTargetWithHttpInfo($authorization, $cloud_name, $id);
        return $response;
    }

    /**
     * Operation getMediaTargetWithHttpInfo
     *
     * Get the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Model\MediaTarget, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMediaTargetWithHttpInfo($authorization, $cloud_name, $id)
    {
        $request = $this->getMediaTargetRequest($authorization, $cloud_name, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Model\MediaTarget' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Model\MediaTarget', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Model\MediaTarget';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Model\MediaTarget',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMediaTargetAsync
     *
     * Get the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaTargetAsync($authorization, $cloud_name, $id)
    {
        return $this->getMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMediaTargetAsyncWithHttpInfo
     *
     * Get the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id)
    {
        $returnType = '\Cloudinary\Model\MediaTarget';
        $request = $this->getMediaTargetRequest($authorization, $cloud_name, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMediaTarget'
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMediaTargetRequest($authorization, $cloud_name, $id)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling getMediaTarget'
            );
        }
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling getMediaTarget'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getMediaTarget'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/media_targets/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMediaTargets
     *
     * Get the Media Targets
     *
     * @param  string $cloud_name Name of the Cloud (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Model\MediaTarget[]
     */
    public function getMediaTargets($cloud_name)
    {
        list($response) = $this->getMediaTargetsWithHttpInfo($cloud_name);
        return $response;
    }

    /**
     * Operation getMediaTargetsWithHttpInfo
     *
     * Get the Media Targets
     *
     * @param  string $cloud_name Name of the Cloud (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Model\MediaTarget[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getMediaTargetsWithHttpInfo($cloud_name)
    {
        $request = $this->getMediaTargetsRequest($cloud_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Model\MediaTarget[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Model\MediaTarget[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Model\MediaTarget[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Model\MediaTarget[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMediaTargetsAsync
     *
     * Get the Media Targets
     *
     * @param  string $cloud_name Name of the Cloud (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaTargetsAsync($cloud_name)
    {
        return $this->getMediaTargetsAsyncWithHttpInfo($cloud_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMediaTargetsAsyncWithHttpInfo
     *
     * Get the Media Targets
     *
     * @param  string $cloud_name Name of the Cloud (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaTargetsAsyncWithHttpInfo($cloud_name)
    {
        $returnType = '\Cloudinary\Model\MediaTarget[]';
        $request = $this->getMediaTargetsRequest($cloud_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMediaTargets'
     *
     * @param  string $cloud_name Name of the Cloud (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMediaTargetsRequest($cloud_name)
    {
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling getMediaTargets'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/media_targets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMediaTarget
     *
     * Update the Media Target
     *
     * @param  string $authorization authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     * @param  \Cloudinary\Model\MediaTargetUpdatePayload $media_target_update_payload Payload to update the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Model\MediaTarget
     */
    public function updateMediaTarget($authorization, $cloud_name, $id, $media_target_update_payload)
    {
        list($response) = $this->updateMediaTargetWithHttpInfo($authorization, $cloud_name, $id, $media_target_update_payload);
        return $response;
    }

    /**
     * Operation updateMediaTargetWithHttpInfo
     *
     * Update the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     * @param  \Cloudinary\Model\MediaTargetUpdatePayload $media_target_update_payload Payload to update the Media Target (required)
     *
     * @throws \Cloudinary\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Model\MediaTarget, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMediaTargetWithHttpInfo($authorization, $cloud_name, $id, $media_target_update_payload)
    {
        $request = $this->updateMediaTargetRequest($authorization, $cloud_name, $id, $media_target_update_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Model\MediaTarget' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Model\MediaTarget', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Model\MediaTarget';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Model\MediaTarget',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateMediaTargetAsync
     *
     * Update the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     * @param  \Cloudinary\Model\MediaTargetUpdatePayload $media_target_update_payload Payload to update the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaTargetAsync($authorization, $cloud_name, $id, $media_target_update_payload)
    {
        return $this->updateMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id, $media_target_update_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMediaTargetAsyncWithHttpInfo
     *
     * Update the Media Target
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     * @param  \Cloudinary\Model\MediaTargetUpdatePayload $media_target_update_payload Payload to update the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaTargetAsyncWithHttpInfo($authorization, $cloud_name, $id, $media_target_update_payload)
    {
        $returnType = '\Cloudinary\Model\MediaTarget';
        $request = $this->updateMediaTargetRequest($authorization, $cloud_name, $id, $media_target_update_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMediaTarget'
     *
     * @param  string $authorization (required)
     * @param  string $cloud_name Name of the Cloud (required)
     * @param  string $id ID of the Media Target (required)
     * @param  \Cloudinary\Model\MediaTargetUpdatePayload $media_target_update_payload Payload to update the Media Target (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateMediaTargetRequest($authorization, $cloud_name, $id, $media_target_update_payload)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling updateMediaTarget'
            );
        }
        // verify the required parameter 'cloud_name' is set
        if ($cloud_name === null || (is_array($cloud_name) && count($cloud_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cloud_name when calling updateMediaTarget'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateMediaTarget'
            );
        }
        // verify the required parameter 'media_target_update_payload' is set
        if ($media_target_update_payload === null || (is_array($media_target_update_payload) && count($media_target_update_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $media_target_update_payload when calling updateMediaTarget'
            );
        }

        $resourcePath = '/{cloud_name}/media_delivery/media_targets/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($cloud_name !== null) {
            $resourcePath = str_replace(
                '{' . 'cloud_name' . '}',
                ObjectSerializer::toPathValue($cloud_name),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($media_target_update_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($media_target_update_payload));
            } else {
                $httpBody = $media_target_update_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
