<?php
/**
 * MediaTargetConfigTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cloudinary\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaTargetConfigTest Class Doc Comment
 *
 * @category    Class
 * @description MediaTargetConfig
 * @package     Cloudinary
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MediaTargetConfigTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MediaTargetConfig"
     */
    public function testMediaTargetConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_bucket_name"
     */
    public function testPropertyS3BucketName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_bucket_folder"
     */
    public function testPropertyS3BucketFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_access_key"
     */
    public function testPropertyS3AccessKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_secret_key"
     */
    public function testPropertyS3SecretKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "s3_uri_template"
     */
    public function testPropertyS3UriTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gs_bucket_name"
     */
    public function testPropertyGsBucketName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gs_bucket_folder"
     */
    public function testPropertyGsBucketFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gs_service_account_key"
     */
    public function testPropertyGsServiceAccountKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gs_uri_template"
     */
    public function testPropertyGsUriTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cld_cloud_name"
     */
    public function testPropertyCldCloudName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
