<?php
/**
 * DeliveryProfileApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\Test\Api;

use \Cloudinary\Configuration;
use \Cloudinary\ApiException;
use \Cloudinary\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeliveryProfileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryProfileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDeliveryProfile
     *
     * Create a new Delivery Profile.
     *
     */
    public function testCreateDeliveryProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDeliveryProfile
     *
     * Delete the Delivery Profile.
     *
     */
    public function testDeleteDeliveryProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeliveryProfile
     *
     * Get the Delivery Profile.
     *
     */
    public function testGetDeliveryProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeliveryProfiles
     *
     * Get the Delivery Profiles.
     *
     */
    public function testGetDeliveryProfiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDeliveryProfile
     *
     * Update the Delivery Profile.
     *
     */
    public function testUpdateDeliveryProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
