<?php
/**
 * MappingFunctionApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\Test\Api;

use \Cloudinary\Configuration;
use \Cloudinary\ApiException;
use \Cloudinary\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MappingFunctionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MappingFunctionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMappingFunction
     *
     * Create a new Mapping Function.
     *
     */
    public function testCreateMappingFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMappingFunction
     *
     * Delete the Mapping Function.
     *
     */
    public function testDeleteMappingFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMappingFunction
     *
     * Get the Mapping Function.
     *
     */
    public function testGetMappingFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMappingFunctions
     *
     * Get the Mapping Functions.
     *
     */
    public function testGetMappingFunctions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMappingFunction
     *
     * Update the Mapping Function.
     *
     */
    public function testUpdateMappingFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
