<?php
/**
 * MediaSourceApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media Delivery
 *
 * Media Delivery API
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\Test\Api;

use \Cloudinary\Configuration;
use \Cloudinary\ApiException;
use \Cloudinary\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediaSourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediaSourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMediaSource
     *
     * Create a new Media Source.
     *
     */
    public function testCreateMediaSource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMediaSource
     *
     * Delete the Media Source.
     *
     */
    public function testDeleteMediaSource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMediaSource
     *
     * Get the Media Source.
     *
     */
    public function testGetMediaSource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMediaSources
     *
     * Get the Media Sources.
     *
     */
    public function testGetMediaSources()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMediaSource
     *
     * Update the Media Source.
     *
     */
    public function testUpdateMediaSource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
